[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.20"
optimizer = true
optimizer_runs = 500
evm_version = "cancun"

[rpc_endpoints]
# Hedera JSON-RPC relays
hedera_testnet = "${HEDERA_TESTNET_RPC_URL}"  # https://testnet.hashio.io/api
hedera_previewnet = "${HEDERA_PREVIEWNET_RPC_URL}"
hedera_mainnet = "${HEDERA_MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
